Update docs to use exclusively Myst Md (#222)
* First attempt at converting to myst md without building docs

* Initial configuration to get myst md notebooks running in docs build

* Update docs dependencies for myst build

* Add ctc example back in using nsphinx link

* Update copyright year

* Remove remaining unresolved merge conflict

* Fix issue with duplicate autoapi objects by dropping back to the previous pinned version of autoapi

* Reorder toctree

* Fix table wrap issue with custom css

* Update tag for removing cell input contents

* Pin docutils to 0.20.* to address issue that appeared in 0.21.2

AttributeError: module 'docutils.nodes' has no attribute 'reprunicode'

* Suppress a sphinx config warning

* Remove cell input on notebook level instead of cell level for track errors

* Enable dollarmath and colonfence myst extensions

* Remove pixi lock file

---------

Co-authored-by: Caroline Malin-Mayor <malinmayorc@janelia.hhmi.org>